### ISSUE TITLE
Adding tag does not work

### ISSUE THREAD

**Issue by anton-trackman** [jasursadikov/mud#40]
Traceback (most recent call last):
  File "/usr/lib/python3.12/xml/etree/ElementTree.py", line 1027, in _escape_attrib
    if "&" in text:
       ^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ada/bin/mud", line 280, in <module>
    cli.run()
  File "/home/ada/bin/mud", line 115, in run
    self.add(args)
  File "/home/ada/bin/mud", line 199, in add
    self.config.save(utils.CONFIG_FILE_NAME)
  File "/home/ada/repos/mud/config.py", line 32, in save
    rough_string = ElementTree.tostring(root, 'utf-8')
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/xml/etree/ElementTree.py", line 1084, in tostring
    ElementTree(element).write(stream, encoding,
  File "/usr/lib/python3.12/xml/etree/ElementTree.py", line 729, in write
    serialize(write, self._root, qnames, namespaces,
  File "/usr/lib/python3.12/xml/etree/ElementTree.py", line 892, in _serialize_xml
    _serialize_xml(write, e, qnames, None,
  File "/usr/lib/python3.12/xml/etree/ElementTree.py", line 885, in _serialize_xml
    v = _escape_attrib(v)
        ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/xml/etree/ElementTree.py", line 1050, in _escape_attrib
    _raise_serialization_error(text)
  File "/usr/lib/python3.12/xml/etree/ElementTree.py", line 1004, in _raise_serialization_error
    raise TypeError(
TypeError: cannot serialize None (type NoneType)

**Comment by jasursadikov** [comment]
Resolved in 6ba4307
