### ISSUE TITLE
pip install mud and then running mud raises ModuleNotFoundError: No module named 'click'

### ISSUE THREAD

**Issue by h0uter** [jasursadikov/mud#69]
I found a solution, the problem is with another [existing package called `mud` too](https://pypi.org/project/mud/).  Posting the process here for posterity.

On python 3.12

```
pip install mud
mud
```

results in

```py
Traceback (most recent call last):
  File "/Users/XXX/Repositories/experiments/src/muddo/.venv/bin/mud", line 5, in <module>
    from mud.cli import cli
  File "/Users/XXX/Repositories/experiments/src/muddo/.venv/lib/python3.12/site-packages/mud/cli.py", line 6, in <module>
    import click
ModuleNotFoundError: No module named 'click'
```

### Solution

`pip install mud-git` not `pip install mud`

**Comment by jasursadikov** [comment]
@h0uter I will close this issue, please tell me if this is still relevant
